service: apollo-lambda
provider:
  name: aws
  runtime: nodejs16.x
plugins:
  - serverless-offline
  - serverless-webpack
custom:
  serverless-offline:
    useChildProcesses: true
  webpack:
    webpackConfig: "webpack.config.js"
    includeModules: true
    packager: "yarn"
    excludeFiles:
functions:
  graphql:
    handler: index.handler
    events:
      - http:
          path: graphql
          method: get
          cors: true
